#!/bin/bash

# Call HaloWiFi API to get all locations attached to your account.
# Details: Call API with token generated by generate-tokens.sh
# Usage: ./get-locations.sh <token>

api_domain="https://one.halowifi.com"
token=$1

location_response=$(curl -X GET "$api_domain/api/external/locations" -H "Authorization: Bearer $token")

# If response status is success print the response else print error message
if echo "$location_response" | jq -e '.status' | grep -q 'success'; then
    echo 
    echo "Getting Locations was successful:"
    echo $location_response
else
    echo 
    echo "Getting Locations failed:"
    echo "$location_response"
fi
